import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

const rows = [
  ["Sampling methodology", "52%", "28 pts", "Critical", "bg-[#b42318]/10 text-[#b42318]"],
  ["Data quality / GSBPM", "68%", "12 pts", "High", "bg-[#e07a2f]/15 text-[#c45c14]"],
  ["Data analysis", "74%", "6 pts", "Medium", "bg-[#16375c]/10 text-[#16375c]"],
  ["Data governance", "86%", "0 pts", "On track", "bg-[#1f6b4a]/15 text-[#1f6b4a]"],
] as const;
export default function AdminPage() { return <div className="space-y-6"><section><Badge>Organisation dashboard · Demo data</Badge><h1 className="mt-2 text-3xl">Capacity-building impact</h1><p className="mt-2 max-w-2xl text-[#3d4f63]">A privacy-conscious aggregate view for training managers. This demo uses synthetic, non-personal organisational data.</p></section><div className="grid gap-4 md:grid-cols-4"><Metric label="Learners" value="248" note="Across 4 departments" /><Metric label="Active this week" value="186" note="75% engagement" /><Metric label="Average competency" value="68%" note="+9 points since baseline" /><Metric label="Critical gaps" value="2" note="Targeted learning required" /></div><Card><h2 className="text-xl">Competency heatmap</h2><p className="mt-1 text-sm text-[#3d4f63]">Use this view to direct training investment to the gaps with the greatest workforce impact.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[580px] text-left text-sm"><thead className="border-b border-[#d9d0c0] text-[#3d4f63]"><tr><th className="pb-3">Competency</th><th className="pb-3">Average score</th><th className="pb-3">Target gap</th><th className="pb-3">Priority</th></tr></thead><tbody>{rows.map(([name, score, gap, priority, cls]) => <tr key={name} className="border-b border-[#e7e0d4]"><td className="py-4 font-semibold">{name}</td><td className="py-4">{score}</td><td className="py-4">{gap}</td><td className="py-4"><Badge className={cls}>{priority}</Badge></td></tr>)}</tbody></table></div></Card><div className="grid gap-4 md:grid-cols-2"><Card><Badge className="bg-[#1f6b4a]/15 text-[#1f6b4a]">Training impact</Badge><h2 className="mt-2 text-xl">Evidence of improvement</h2><p className="mt-3 text-sm text-[#3d4f63]">Sampling cohort: baseline 46% → post-learning 72%.</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-[#e7e0d4]"><div className="h-full rounded-full bg-[#1f6b4a]" style={{ width: "72%" }} /></div><p className="mt-2 text-sm font-semibold text-[#1f6b4a]">+26 competency points after assessment, practice, and revision.</p></Card><Card><Badge>iGOT integration readiness</Badge><h2 className="mt-2 text-xl">Integration boundary is in place</h2><p className="mt-3 text-sm text-[#3d4f63]">Current mode: LOCAL DEMO DATA. Courses, users, progress and authentication are deliberately separated for a credentialed iGOT connector when authorised API documentation becomes available.</p></Card></div></div>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <Card><div className="text-xs font-semibold uppercase tracking-wide text-[#3d4f63]">{label}</div><div className="mt-1 font-serif text-3xl">{value}</div><p className="mt-1 text-sm text-[#3d4f63]">{note}</p></Card>; }
