"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/utils";

type Audit = { role: string; coverage: { competency_id: string; competency: string; required: number; coverage: "Covered" | "Partially covered" | "Missing"; evidence_terms: string[] }[]; summary: { covered: number; partial: number; missing: number }; recommendation: string; disclaimer: string };
const sample = "This course introduces stratified sampling, sampling weights, survey fieldwork, data quality checks, GSBPM, confidentiality, CAPI and SDMX metadata. Learners practise interpreting survey results.";
const styles = { Covered: "bg-[#1f6b4a]/15 text-[#1f6b4a]", "Partially covered": "bg-[#e07a2f]/15 text-[#c45c14]", Missing: "bg-[#b42318]/10 text-[#b42318]" };
export function CourseAuditor() { const [text, setText] = useState(sample); const [role, setRole] = useState("Statistical Officer"); const [audit, setAudit] = useState<Audit | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); async function run() { setBusy(true); setError(null); try { setAudit(await api<Audit>("/api/intelligence/course-audit", { method: "POST", body: JSON.stringify({ course_text: text, role }) })); } catch { setError("Course audit needs the local backend running."); } finally { setBusy(false); } } return <Card><div className="flex flex-wrap items-end justify-between gap-3"><div><Badge>Trainer intelligence</Badge><h2 className="mt-2 text-xl">Course–competency auditor</h2><p className="mt-1 text-sm text-[#3d4f63]">Check whether a course covers the configured role framework before human review.</p></div><label className="text-sm font-semibold">Role <select className="ml-2 rounded-lg border border-[#d9d0c0] bg-white p-2 font-normal" value={role} onChange={(event) => setRole(event.target.value)}><option>Statistical Officer</option><option>Survey Officer</option><option>Data Analyst</option></select></label></div><textarea aria-label="Course material to audit" className="mt-4 min-h-28 w-full rounded-xl border border-[#d9d0c0] p-3 text-sm" value={text} onChange={(event) => setText(event.target.value)} /><Button className="mt-3" disabled={busy || text.trim().length < 40} onClick={run}>{busy ? "Checking…" : "Audit course coverage"}</Button>{error ? <p className="mt-3 text-sm text-[#b42318]">{error}</p> : null}{audit ? <div className="mt-5"><div className="flex flex-wrap gap-2"><Badge className={styles.Covered}>{audit.summary.covered} covered</Badge><Badge className={styles["Partially covered"]}>{audit.summary.partial} partial</Badge><Badge className={styles.Missing}>{audit.summary.missing} missing</Badge></div><div className="mt-3 space-y-2">{audit.coverage.map((row) => <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[#e7e0d4] p-3 text-sm" key={row.competency_id}><span><strong>{row.competency}</strong><span className="ml-2 text-[#3d4f63]">Required {row.required}%{row.evidence_terms.length ? ` · evidence: ${row.evidence_terms.join(", ")}` : ""}</span></span><Badge className={styles[row.coverage]}>{row.coverage}</Badge></div>)}</div><p className="mt-3 text-sm text-[#3d4f63]"><strong>Trainer recommendation:</strong> {audit.recommendation}</p><p className="mt-2 text-xs text-[#3d4f63]">{audit.disclaimer}</p></div> : null}</Card>; }
