"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { learnerMemory } from "@/lib/memory";
import { api } from "@/lib/utils";

type Result = { topic_state: { topic: string; state: string; mastery: number; accuracy: number | null }; intervention: { intervention: string; why: string; gap: number }; difficulty_curve: { sequence: string[]; rationale: string }; revision: { memory_risk: string; due: string; minutes: number; pack: string[] }; what_if: { label: string; projected: number; projected_gain: number; assumption: string }; disclaimer: string };

export function LearningIntelligencePanel() {
  const [minutes, setMinutes] = useState(30); const [focus, setFocus] = useState(true); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState<string | null>(null);
  async function refresh() { const memory = learnerMemory(); try { setError(null); setResult(await api<Result>("/api/twin/learning-intelligence", { method: "POST", body: JSON.stringify({ ...memory, daily_minutes: minutes, days: 30, focus_first: focus, days_since_review: memory.last_session ? Math.floor((Date.now() - new Date(memory.last_session.at).getTime()) / 86400000) : 7 }) })); } catch { setError("Learning intelligence is available when the local backend is running."); } }
  useEffect(() => { void refresh(); }, []);
  return <Card><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge className="bg-[#e07a2f]/15 text-[#c45c14]">Learner memory → intervention</Badge><h2 className="mt-2 text-xl">Personalise the next evidence step</h2><p className="mt-1 text-sm text-[#3d4f63]">Uses only browser-local profile, practice, revision and session signals.</p></div><div className="flex flex-wrap items-center gap-2 text-sm"><label>Minutes/day <input aria-label="Minutes per day" className="ml-1 w-16 rounded border border-[#d9d0c0] p-2" min="5" max="180" type="number" value={minutes} onChange={(event) => setMinutes(Number(event.target.value) || 5)} /></label><label className="flex items-center gap-1"><input type="checkbox" checked={focus} onChange={(event) => setFocus(event.target.checked)} /> Focus priority first</label><Button onClick={refresh}>Update</Button></div></div>{error ? <p className="mt-4 text-sm text-[#b42318]">{error}</p> : null}{result ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Insight title="Learning state" value={result.topic_state.state} note={`${result.topic_state.topic} · ${result.topic_state.mastery}% mastery`} /><Insight title="Best intervention" value={result.intervention.intervention} note={result.intervention.why} /><Insight title="Difficulty curve" value={result.difficulty_curve.sequence.join(" → ")} note={result.difficulty_curve.rationale} /><Insight title={`Memory risk: ${result.revision.memory_risk}`} value={`${result.revision.minutes}-minute revision ${result.revision.due}`} note={result.revision.pack.join(" · ")} /></div> : null}{result ? <div className="mt-4 rounded-xl bg-[#16375c]/5 p-4 text-sm"><Badge>{result.what_if.label}</Badge><strong className="ml-2">{result.topic_state.topic}: {result.topic_state.mastery}% → estimated {result.what_if.projected}%</strong><span className="ml-2 text-[#3d4f63]">(+{result.what_if.projected_gain} points in 30 days). {result.what_if.assumption}</span></div> : null}</Card>;
}
function Insight({ title, value, note }: { title: string; value: string; note: string }) { return <div className="rounded-xl border border-[#d9d0c0] p-3"><div className="text-xs font-semibold uppercase tracking-wide text-[#c45c14]">{title}</div><div className="mt-1 font-semibold">{value}</div><p className="mt-2 text-xs text-[#3d4f63]">{note}</p></div>; }
