"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/utils";

type Node = { id: string; type: string; label: string }; type Edge = { from: string; to: string; rel: string }; type Graph = { nodes: Node[]; edges: Edge[]; disclaimer: string };
const colours: Record<string, string> = { role: "bg-[#16375c] text-white", competency: "bg-[#e07a2f] text-white", topic: "bg-[#f4efe4] text-[#102033]", resource: "bg-[#1f6b4a] text-white", assessment: "bg-[#c4a15a] text-[#102033]", mastery: "bg-[#102033] text-white" };
export default function GraphPage() { const [graph, setGraph] = useState<Graph | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { api<Graph>("/api/intelligence/graph").then(setGraph).catch(() => setError("The knowledge graph needs the local backend running on port 8000.")); }, []); const node = (id: string) => graph?.nodes.find((item) => item.id === id)?.label ?? id; return <div className="space-y-6"><section><Badge>Future-ready knowledge graph</Badge><h1 className="mt-2 text-3xl">Connect role requirements to verified mastery</h1><p className="mt-2 max-w-2xl text-[#3d4f63]">This makes the reasoning chain inspectable: role → competency → topic → resource → assessment → mastery.</p></section>{error ? <Card className="border-[#b42318] text-sm text-[#b42318]">{error}</Card> : null}{graph ? <><Card><div className="flex flex-wrap gap-2">{graph.nodes.map((item) => <span key={item.id} className={`rounded-xl px-3 py-2 text-sm font-semibold ${colours[item.type] ?? "bg-[#f4efe4]"}`}>{item.label}<small className="ml-2 opacity-75">{item.type}</small></span>)}</div></Card><Card><h2 className="text-xl">Relationships</h2><div className="mt-4 space-y-2">{graph.edges.map((edge) => <div key={`${edge.from}-${edge.to}-${edge.rel}`} className="flex flex-wrap items-center gap-2 rounded-lg bg-[#f4efe4] p-3 text-sm"><strong>{node(edge.from)}</strong><span className="rounded bg-white px-2 py-1 text-xs text-[#c45c14]">{edge.rel.replaceAll("_", " ")}</span><span>→</span><strong>{node(edge.to)}</strong></div>)}</div></Card><p className="text-xs text-[#3d4f63]">{graph.disclaimer}</p></> : null}</div>; }
