"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { getTopics, readiness, type SyllabusTopic } from "@/lib/learner";

const colour: Record<SyllabusTopic["status"], string> = { "Mastered": "bg-[#1f6b4a]/15 text-[#1f6b4a]", "Review": "bg-[#16375c]/10 text-[#16375c]", "Practising": "bg-[#e07a2f]/15 text-[#c45c14]", "Learning": "bg-[#e07a2f]/15 text-[#c45c14]", "Weak": "bg-[#b42318]/10 text-[#b42318]", "Not started": "bg-[#3d4f63]/10 text-[#3d4f63]" };
export default function SyllabusPage() { const [topics, setTopics] = useState<SyllabusTopic[]>([]); useEffect(() => setTopics(getTopics()), []); const grouped = topics.reduce<Record<string, SyllabusTopic[]>>((out, topic) => ({ ...out, [topic.subject]: [...(out[topic.subject] ?? []), topic] }), {}); return <div className="space-y-6"><section><Badge>Syllabus mastery</Badge><h1 className="mt-2 text-3xl">Every topic has a next step.</h1><p className="mt-2 text-[#3d4f63]">Mastery requires learning, practice, quiz evidence and revision—not simply opening a lesson.</p></section><Card><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{topics.filter((topic) => topic.status === "Mastered").length}/{topics.length} topics mastered</strong><p className="mt-1 text-sm text-[#3d4f63]">Readiness across this demo syllabus: {readiness(topics)}%</p></div><div className="h-3 w-56 overflow-hidden rounded-full bg-[#e7e0d4]"><div className="h-full rounded-full bg-[#1f6b4a]" style={{ width: `${readiness(topics)}%` }} /></div></div></Card>{Object.entries(grouped).map(([subject, items]) => <section key={subject}><h2 className="text-xl">{subject}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{items.map((topic) => <Card key={topic.id}><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase text-[#3d4f63]">{topic.unit}</div><h3 className="mt-1 text-lg">{topic.title}</h3></div><Badge className={colour[topic.status]}>{topic.status}</Badge></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#e7e0d4]"><div className="h-full rounded-full bg-[#16375c]" style={{ width: `${topic.mastery}%` }} /></div><p className="mt-2 text-sm text-[#3d4f63]">Mastery {topic.mastery}% · {topic.importance} exam priority</p><Link href={`/study?topic=${topic.id}`} className="mt-3 inline-block"><Button variant="secondary">{topic.mastery ? "Continue" : "Start learning"}</Button></Link></Card>)}</div></section>)}</div>; }
